# Adds YAML Schema support for VSCode users with the YAML extension installed. This enables features like validation and autocompletion based on the provided schema.
# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
config:
  edition: 3

streams:
  spike_transactions:
    auto_subscribe: true
    query: |
      SELECT * FROM spike.transactions
      WHERE household_id IN (
        SELECT household_id FROM spike.membership WHERE user_id = auth.user_id()
      )
