import { defineConfig } from "oxlint";
// @ts-expect-error - no types for oxlint-config
import strict from "@rnx-kit/oxlint-config";

export default defineConfig({
  extends: [strict],
  plugins: ["import", "react"],
  categories: {
    correctness: "off",
  },
  env: {
    builtin: true,
    es2022: true,
    browser: true,
  },
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    "anti-slop-effect/no-service-constructor-imports": "error",
    complexity: ["error", { max: 10 }],
    "import/namespace": "error",
    "import/export": "error",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "warn",
    "import/no-duplicates": "warn",
    eqeqeq: ["warn", "smart"],
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty-character-class": "warn",
    "no-empty-pattern": "warn",
    "no-extend-native": "warn",
    "no-extra-bind": "warn",
    "no-redeclare": "warn",
    "no-undef": "error",
    "no-unreachable": "warn",
    "no-unsafe-negation": "warn",
    "no-unused-expressions": [
      "warn",
      {
        allowShortCircuit: true,
        enforceForJSX: true,
      },
    ],
    "no-unused-labels": "warn",
    "no-unused-vars": [
      "warn",
      {
        vars: "all",
        args: "none",
        ignoreRestSiblings: true,
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
      },
    ],
    "no-with": "warn",
    "unicode-bom": ["warn", "never"],
    "use-isnan": "error",
    "valid-typeof": "error",
    "import/first": "warn",
    "no-var": "error",
    "react/display-name": "error",
    "react/jsx-key": "error",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-undef": "error",
    "react/no-children-prop": "error",
    "react/no-danger-with-children": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-find-dom-node": "error",
    "react/no-is-mounted": "error",
    "react/no-render-return-value": "error",
    "react/no-string-refs": "error",
    "react/no-unescaped-entities": "error",
    "react/no-unknown-property": "warn",
    "react/require-render-return": "error",
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "react/no-this-in-sfc": "warn",
    "expo/use-dom-exports": ["error"],
    "expo/no-env-var-destructuring": ["error"],
    "expo/no-dynamic-env-var": ["error"],
  },
  globals: {
    exports: "readonly",
    global: "readonly",
    module: "readonly",
    require: "readonly",
    AudioWorkletGlobalScope: "readonly",
    AudioWorkletProcessor: "readonly",
    currentFrame: "readonly",
    currentTime: "readonly",
    registerProcessor: "readonly",
    sampleRate: "readonly",
    WorkletGlobalScope: "readonly",
    __DEV__: "readonly",
    ErrorUtils: "readonly",
    clearImmediate: "readonly",
    process: "readonly",
    setImmediate: "readonly",
    "shared-node-browser": "writable",
  },
  ignorePatterns: [
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/oxlint/anti-slop/**",
    "android/app/build",
    "**/dist/**",
    "**/.alchemy/**",
  ],
  jsPlugins: [
    "eslint-plugin-expo",
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    {
      name: "anti-slop-effect",
      specifier: "./tools/oxlint/anti-slop/effect/index.ts",
    },
  ],
  overrides: [
    {
      files: ["**/metro.config.js", "apps/mobile/scripts/**/*.js", "apps/mobile/scripts/**/*.mjs"],
      env: {
        node: true,
      },
    },
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.d.ts"],
      rules: {
        "@typescript-eslint/array-type": [
          "warn",
          {
            default: "array",
          },
        ],
        "@typescript-eslint/no-empty-object-type": "warn",
        "@typescript-eslint/no-wrapper-object-types": "warn",
        "@typescript-eslint/consistent-type-assertions": [
          "warn",
          {
            assertionStyle: "as",
            objectLiteralTypeAssertions: "allow",
          },
        ],
        "@typescript-eslint/no-extra-non-null-assertion": "warn",
        "no-unused-vars": "error",
        "no-useless-constructor": "warn",
        "no-undef": "error",
        "@typescript-eslint/no-require-imports": [
          "warn",
          {
            allow: [
              "\\.(aac|aiff|avif|bmp|caf|db|gif|heic|html|jpeg|jpg|json|m4a|m4v|mov|mp3|mp4|mpeg|mpg|otf|pdf|png|psd|svg|ttf|wav|webm|webp|xml|yaml|yml|zip)$",
            ],
          },
        ],
      },
      plugins: ["typescript"],
    },
    {
      // test patterns
      files: [
        "**/*.test.ts",
        "**/*.test.tsx",
        "apps/mobile/jest/setup-env.ts",
        "apps/mobile/tests/**/*.ts",
        "apps/mobile/tests/**/*.{ts,tsx}",
      ],
      plugins: ["jest"],
      env: {
        "jest/globals": true,
      },
      rules: {
        "typescript/no-require-imports": "off",
      },
      globals: {
        jest: "readonly",
        describe: "readonly",
        expect: "readonly",
        it: "readonly",
        beforeAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
      },
    },
  ],
});
