/** @type {import("jest").Config} */
module.exports = {
  preset: "jest-expo",
  modulePathIgnorePatterns: ["<rootDir>/e2e"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
    "^@expo/ui$": "<rootDir>/jest/mocks/expo-ui.tsx",
    "^@rn-primitives/slot$": "<rootDir>/jest/mocks/slot.js",
    "^.+\\.css$": "<rootDir>/jest/mocks/style.js",
  },
  setupFiles: ["react-native-gesture-handler/jestSetup"],
  setupFilesAfterEnv: ["<rootDir>/jest/setup-env.ts"],
  transform: {
    "\\.mjs$": "babel-jest",
  },
  testEnvironmentOptions: {
    localStorage: {},
    sessionStorage: {},
  },
  transformIgnorePatterns: [
    "/node_modules/(?!(.pnpm|react-native|@react-native|@react-native-community|expo|expo-modules-core|@expo|@expo-google-fonts|react-navigation|@react-navigation|@sentry/react-native|native-base|@rn-primitives|number-flow-react-native|phosphor-react-native|@powersync|@tanstack/db|@tanstack/react-db|@tanstack/powersync-db-collection|@tanstack/db-ivm|@tanstack/pacer-lite|fractional-indexing|p-defer))",
    "/node_modules/react-native-reanimated/plugin/",
  ],
  collectCoverageFrom: [
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "hooks/**/*.{ts,tsx}",
    "modules/**/*.{ts,tsx}",
    "stores/**/*.{ts,tsx}",
    "utils/**/*.{ts,tsx}",
    "lib/**/*.{ts,tsx}",
    "!**/*.d.ts",
    "!types/**",
    "!db/**",
    "!**/__tests__/**",
    "!**/*.test.{ts,tsx}",
    "!**/*.spec.{ts,tsx}",
    "!app.config.ts",
    "!babel.config.js",
    "!metro.config.js",
    "!scripts/**",
    "!__tests__/fixtures/**",
    "!**/types.ts",
  ],
  coverageReporters: ["json", "lcov", ["text", { skipFull: true }]],
  coverageThreshold: {
    global: {
      branches: 45,
      functions: 55,
      lines: 55,
      statements: 55,
    },
    "./utils/currency.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    "./utils/date.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    "./utils/transaction.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    "./utils/recurring.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    "./utils/journal-list.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    "./stores/ui-store.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    "./hooks/use-num-pad-number.ts": {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
};
